export const ListOfShopServices = [
  "Oil Change",
  "Brake Pad Replacement",
  "Tire Rotation",
  "Battery Replacement",
  "Engine Tune-Up",
  "Air Conditioning Repair",
  "Wheel Alignment",
  "Transmission Flush",
  "Fuel System Cleaning",
  "Coolant Flush",
  "Timing Belt Replacement",
  "Suspension Repair",
  "Exhaust System Repair",
  "Electrical System Repair",
  "Steering System Repair",
];
